lib/validators/doc-media-validator.ts
test/validators/doc-media-validator.test.ts

Without it does not work at all in the Digital Editor, so this check was wrong. Tested a social media component without "media-properties" in the Digital Editor, and it will fail because it cannot show the dialog. So this should never have been allowed.
Refactor code to remove all the nesting (improving readability) and include the component name in the error messages.

Change validation check for doc-media directive to not allow the directive without a "media-properties" component property.

---

README.md
lib/index.ts
lib/validators/package-validator.ts
test/index.test.ts

Static validateSize method is to be used in ecs-backed directly to validate the size of the zip file before unpacking it.

ECS-368: Extract top level package validation in a static method

---

lib/index.ts
package-lock.json
package.json
test/index.test.ts
test/resources/minimal-sample-invalid-comp-property/components-definition.json
test/resources/minimal-sample-invalid-comp-property/icons/component.svg
test/resources/minimal-sample-invalid-comp-property/localization/enUS.json
test/resources/minimal-sample-invalid-comp-property/styles/_body.scss
test/resources/minimal-sample-invalid-comp-property/templates/html/body.html

TBD on formatting the error messages, so this is a draft for now.
Add validation test that shows the error message.
Output for example when running with schema version 1.5.0, but not having removed the deprecated "disable-fullscreen-checkbox":
```sh
> csde-components-boilerplate@1.4.0 build /Users/sandern/inception/csde-components-boilerplate
> gulp
[12:37:06] Using gulpfile ~/inception/csde-components-boilerplate/gulpfile.js
[12:37:06] Starting 'default'...
[12:37:06] Starting 'compileDesignFile'...
[12:37:06] Starting 'generateVendorScript'...
[12:37:08] Finished 'generateVendorScript' after 2.64 s
[12:37:08] Finished 'compileDesignFile' after 2.64 s
[12:37:08] Starting 'validate'...
/componentProperties/10/control should have required property 'options'
{
"missingProperty": "options"
} …
```

Show source & line number for schema errors.

---

package.json

Can be used by Webpack tree shaking to reduce bundle size.
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

scout: mark package as side effect free.

---

lib/validators/properties-validator.ts
test/validators/properties-validator.test.ts

The only type of property that should be allowed without name is the header, which does not save data
into the article. Other properties require a name, as it is used as the key for data saving.
I start to feel we should also have a fresh look at the validators structure:
- The tests feel a bit clumsy. I would rather have tools to create real component set structures in an easy way, rather than these incomplete snippets.
- The validators itself could use more structure, like I now need to pass through the ParsedComponent reference to build the error message.
- We need a way to easily show where the user made the mistake, with line numbers in the components-definition.json. Acting on the parsed ComponentSet structure might make this hard though.

CSH-8048: only allow nameless properties for header properties.

---

lib/components-schema-v1_7_x.ts
lib/models/components-definition.ts
lib/parser/parser-utils.ts
lib/validate.ts
package.json
test/parser/parser-util.child-properties.test.ts
test/resources/minimal-sample-next/components-definition.json

* Parses the child properties and builds the default component content when child properties are set.
* Adds JSON schema typing
Does not validate that child property names are unique for the component yet.

ECS-395 parse child properties

---

lib/components-schema-v1_7_x.ts
lib/validators/properties-validator.ts
test/resources/minimal-sample-next/components-definition.json
test/validators/properties-validator.test.ts

Restricts the inline properties in the component's properties array to just inline header property definitions and references to existing component properties overriding the directive key.
```
{ control: { type: 'header' }, label: 'Header Label' },
```
```
{ "name": "hyperlink", "directiveKey": "hyperlink" }
```
Adds validation that verifies that parsed header properties have no dataType property

Restrict inline properties

---

package-lock.json
package.json

Remove no longer needed @types/htmlparser2, as it now includes typings itself.

boyscout: update htmlparser2 to latest version.

---

package-lock.json
package.json

Release as patch version as no functionality changes.

Bump validator version to 1.14.1

---

lib/parser/parser-utils.ts

The getFileContent function can take care of normalising the path if it wants.
By not calling path here, we should not need to include a path polyfill in our code.

CSH-8382: remove path.normalise in parser util.

---

package-lock.json
package.json

Patch release since no new functionality.

Bump validator version to 1.15.1

---

package-lock.json
package.json

Patch since it fixes just a missing type.

Bump validator version to 1.15.2

---

lib/models/components-definition.ts

Makes it possible to filter for properties with a specific type of control and add a matching type.

scout: make typing more flexible

---

lib/models/component-set.ts

These are optional in `ComponentsDefinition`, but `parseDefinition` guarantees that they always exist in `ComponentSet`.

scout: Unmark properties as optional

---

.eslintrc.js
lib/validators/package-validator.ts
tsconfig.json

Noticed warnings about unused imports in the IDE. Turns them into errors through TS.

scout: tighten ts code checking

---

README.md
lib/models/get-file-content.ts
lib/parser/parser-utils.ts
lib/renditions/index.ts
lib/renditions/utils.ts
lib/util/freeze.ts
lib/validate.ts
lib/validators/components-validator.ts
test/parser/parser-util.child-properties.test.ts
test/parser/parser-util.test.ts

Fixes the problem in ecs backend where the filePaths and getFileContent paths no longer match because one is normalized and the other isn't. Also keeps the getFileContent, getFileSize and filePaths arguments of the validate function consistent: all take normalized paths. The problem of having a path.normalize in the browser is solved by separating the loading of the renditions is a separate function that is not imported in the browser when using parseDefinition. Additionally adds deepFreeze to ensure the components definition is not altered while parsing it into a component set.

CSH-8382: roll back 523b8ba and solve in a different way

---

.github/workflows/release.yml
package-lock.json
package.json

- Update workflow action
- Create new patch release to test out publish to GitHub packages.

Ecs 428 publish to GitHub packages

---

lib/definition/component-info.ts
lib/models/component-set.ts
lib/models/components-definition.ts
lib/parser/parser-utils.ts
lib/renditions/utils.ts
lib/validators/autofill-validator.ts
lib/validators/default-component-on-enter-override-validator.ts
lib/validators/default-values-validator.ts
lib/validators/directive-options-validator.ts
lib/validators/directive-properties-validator.ts
lib/validators/disable-fullscreen-checkbox-validator.ts
lib/validators/doc-container-groups-validator.ts
lib/validators/doc-container-validator.ts
lib/validators/doc-media-validator.ts
lib/validators/doc-slideshow-validator.ts
lib/validators/drop-capital-validator.ts
lib/validators/fitting-validator.ts
lib/validators/focuspoint-validator.ts
lib/validators/image-editor-validator.ts
lib/validators/interactive-validator.ts
lib/validators/properties-validator.ts
lib/validators/restrict-children-validator.ts
lib/validators/slides-validator.ts
lib/validators/strip-styling-on-paste-validator.ts
lib/validators/unit-type-validator.ts

- Rename `Component` to `ComponentDefinition` 
- Rename `ParsedComponent` to `Component` (which is really the main type we would use).
I checked usage of `ParsedComponent` in the Digital Editor and not too many direct usages. So updating should be trivial.
As per ticket I also looked if we could change `Label` to `string` for the final type of the component set, as in the client it is always already translated. However this seems to result in a mess of types (not trivial to keep clean).

Csh 6552 improve types

---

lib/validators/properties-validator.ts
test/validators/properties-validator.test.ts

Doesn't make sense as "styles" or "inlineStyles", as in that case it will be added as styling to the dom. But the data is an object, so that would just result in weird behavior.

boyscout: restrict data type for new object-select property.

---

lib/components-schema-v1_9_x.ts
lib/models/component-property-controls.ts
lib/models/components-definition.ts
lib/validators/properties-validator.ts
test/resources/minimal-sample-next/components-definition.json
test/validate.test.ts
test/validators/properties-validator.test.ts

This is used to indicate the data refers to an object in Studio.
When a property is created with this data type, it ensures placed relations are created with that object.
For now it can only be used with the experimental "object-select" UI control type.
Archiving to assets is not supported (the image will not be picked up).

CSH-8707: introduce object data type.

---

lib/validate.ts

Will check in a separate PR how to improve the tests. So we need some unit tests that try different combinations. With the previous code "1.9.0-next" was no longer valid...

boyscout: fix schema version too strict for 1.9.0

---

README.md
lib/definition/component-info.ts
lib/models/component-set-info.ts
lib/models/components-definition.ts
lib/parser/parser-utils.ts
lib/validate.ts
test/definition/component-info.test.ts
test/definition/process-templates.test.ts
test/resources/minimal-sample/components-definition.json

Information will be used in the Studio plug-in while parsing the article to find all `studio-object-select` properties.

CSH-8877: Add component property info to the partial info definition

---

.github/workflows/build.yml
.github/workflows/prerelease.yml
.github/workflows/release.yml
package-lock.json

- Update package lock to v2
- Update GitHub workflow actions to use Node 16.

Ecs 544 update node 16 npm 8

---

package-lock.json
package.json

Include experimental definition for "anchor" property and adds "any-value" match type. Available in component definition schema 1.10.0-next.

Bump validator version to 1.20.0

---

lib/models/components-definition.ts

Makes it easier to work with the various types, to be used in: https://github.com/WoodWing/contentstation/pull/3736

boyscout: Split out component conversion rule types

---

lib/models/component-property-controls.ts
lib/validators/directive-properties-validator.ts
lib/validators/doc-chart-validator.ts
test/validators/doc-chart-validator.test.ts

There was a difference between the schema definition declaring `chart` in componentPropertyDefinition while validators were still checking for the old value `chart-properties`. 
Tests did not complain as we only test minimal sample, which don't include all components.

Rename chart-properties to just chart in validators

---

lib/components-schema-v1_11_x.ts
lib/models/component-property-controls.ts
lib/validators/doc-chart-validator.ts
test/test-utils.ts
test/validate.chart.test.ts
test/validators/doc-chart-validator.test.ts

As requested in this PR https://github.com/WoodWing/contentstation/pull/4809#discussion_r1422291715
In case we want to support different chartTypes or chart providers, not just **Infogram**, then we have a way to distinguish them.

CSH-10045: Add `chartType` property

---

lib/components-schema-v1_11_x.ts
lib/validators/unit-type-validator.ts
test/validators/unit-type-validator.test.ts

In order to customise the chart-component height, we need to be able to set a `padding-bottom` percentage, this way we can respect the aspect ratio, that is needed for any chart ([similar to the embed component](https://github.com/WoodWing/csde-components-boilerplate/blob/fd4b1b8b123737aab3f4fe546007d552fc0b60a1/component-sets/default-components/styles/_embed.scss#L8)).

CSH-10063-Add-percentage-as-unit-in-for-text-property-fields
