WoodWing/studio-component-set-tools

lib/parser/parser-utils.ts
lib/validators/validator.ts
package-lock.json
package.json

Fix compile errors due new TypeScript version.

chore: update Jest & TypeScript to latest version.

---

jest.config.js
lib/index.ts
package-lock.json
package.json

Used for schema validation.
After that I want to look into https://github.com/ajv-validator/ajv/issues/763 if I have some time. It would be really nice to map back the errors to the json source.

Update avj to latest version

---

.eslintrc.js
lib/components-schema-v1_0_x.ts
lib/components-schema-v1_1_x.ts
lib/components-schema-v1_2_x.ts
lib/components-schema-v1_3_x.ts
lib/components-schema-v1_4_x.ts
lib/components-schema-v1_5_x.ts
lib/index.ts
lib/models/component-property-controls.ts
lib/models/components-definition.ts
lib/models/get-file-content.ts
lib/models/label.ts
lib/parser/parser-utils.ts
lib/util/files.ts
lib/validators/default-values-validator.ts
lib/validators/icons-validator.ts
lib/validators/localization-validator.ts
lib/validators/package-validator.ts
lib/validators/slides-validator.ts
package-lock.json
package.json
test/index.test.ts
test/parser/parser-util.test.ts
test/validators/autofill-validator.test.ts
test/validators/doc-container-groups-validator.test.ts
test/validators/doc-media-validator.test.ts
tsconfig.json
types/json-source-map/index.d.ts

For now this PR is based on the feature/eslint branch. It only contains the fixes for the issues in the lib folder. The fixes for the test folder will follow in a separate PR.

Fixed the eslint errors in the lib folder.

---

lib/components-schema-v1_6_x.ts
lib/models/component-property-controls.ts
lib/models/components-definition.ts
lib/parser/parser-utils.ts
lib/validators/default-values-validator.ts
test/resources/minimal-sample-1_6_x/components-definition.json
test/validators/default-values-validator.test.ts

Requires configuring default value, minValue, maxValue and stepSize.

ECS-390: add slider control type property.

---

README.md
lib/components-schema-v1_7_x.ts
lib/validate.ts
package-lock.json
package.json
test/resources/minimal-sample-next/components-definition.json
test/resources/minimal-sample-next/icons/component.svg
test/resources/minimal-sample-next/localization/enUS.json
test/resources/minimal-sample-next/styles/_body.scss
test/resources/minimal-sample-next/styles/_intro.scss
test/resources/minimal-sample-next/templates/html/body.html
test/resources/minimal-sample-next/templates/html/container.html
test/resources/minimal-sample-next/templates/html/intro.html
test/validate.test.ts

Update readme with instructions on how to deal with releasing new schema version and how to handle
the prerelease version.
This "1.7.0-next" version can be used for development until we decide to release it. After that we can immediately introduce the "1.8.0-next" version.

scout: introduce 1.7.0-next version for development.

---

lib/validate.ts
package-lock.json
package.json
test/validate.test.ts

And switch from red to bright red to improve readability.

chore: replace unmaintained colors with chalk

---

lib/validators/properties-validator.ts
test/resources/minimal-sample-next/components-definition.json
test/validators/properties-validator.test.ts

- restructures the tests (1st commit)
- adds child properties validation (2nd commit)

ECS-395 validate child properties

---

README.md
lib/components-schema-v1_8_x.ts
test/resources/minimal-sample-next/components-definition.json

If I am not mistaken, there is nothing more to it than this.

CSH-8342: Add dynamicCaptions property

---

lib/components-schema-v1_7_x.ts
lib/components-schema-v1_8_x.ts
lib/validators/conversion-rules-validator.ts
package-lock.json
package.json

Change npm run scripts to use double quotes: https://stackoverflow.com/questions/48078281/run-prettier-on-windows
Prep to also run github action on windows if not too many problems are encountered (but will need to experiment more).

Update prettier to latest version

---

.gitattributes
.github/workflows/build.yml
lib/validators/custom-styles-validator.ts

Run tests on Windows. One failing test due normalisation of paths. I do wonder how we want to deal with path normalisation. In the backend we always want to store the paths the same way.

CSH-8382: Add windows runner

---

lib/models/behavior-type-guards.ts
lib/models/component-property-controls.ts
lib/models/index.ts
lib/models/type-guards.ts

- Add typeguards for all `ComponentPropertyControl` types
- Add behavior typeguard for component property controls that support dynamic captions (currently just select)

CSH-8344: type guards

---

package-lock.json
package.json

Bump version to 1.15.3

---

package-lock.json
package.json

Bump version to 1.15.4

---

package-lock.json
package.json

Patch version since characterStyles are still experimental (part of next version).

Bump validator version to 1.16.6

---

lib/validate.ts
package-lock.json
package.json
test/validate.test.ts

https://github.com/ajv-validator/ajv/releases/tag/v8.0.0

boyscout: update avj to latest version.

---

lib/components-schema-v1_9_x.ts
lib/models/component-property-controls.ts
test/resources/minimal-sample-next/components-definition.json
test/validate.test.ts

For this task review if the initial API design is good enough.

CSH-8655: add experimental property definition for selecting objects (such as images).

---

package-lock.json
package.json

studio-object data type + rename object-select to studio-object-select.

Bump validator version to 1.17.1

---

lib/components-schema-v1_10_x.ts
lib/components-schema-v1_9_x.ts

The validator would not complain when leaving out properties or when making typos.

boyscout: define required properties of character styles.

---

package-lock.json
package.json

Make character styles validation more strict.

Bump validator version to 1.18.2

---

jest.config.js
lib/validate.ts
package-lock.json
package.json
test/validate.test.ts

Faster, but not as much as in other projects.

refactor: replace ts-jest with @swc/jest
